//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.DataService.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpDesk.DataService.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запись удалена ранее другим пользователем.
        /// </summary>
        internal static string AnotherUserDeleteRecordConstraintMsg {
            get {
                return ResourceManager.GetString("AnotherUserDeleteRecordConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Апрель.
        /// </summary>
        internal static string April {
            get {
                return ResourceManager.GetString("April", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Август.
        /// </summary>
        internal static string August {
            get {
                return ResourceManager.GetString("August", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другой пользователь изменил состояние записи. Требуется обновить журнал.
        /// </summary>
        internal static string ConcurrencyConstraintMsg {
            get {
                return ResourceManager.GetString("ConcurrencyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для совершения операции требуется выбрать корреспондента.
        /// </summary>
        internal static string CorrespondentUserConstraintMsg {
            get {
                return ResourceManager.GetString("CorrespondentUserConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата должна быть не меньше текущей {0:dd.MM.yyyy HH:mm}.
        /// </summary>
        internal static string DataMinConstraintMsg {
            get {
                return ResourceManager.GetString("DataMinConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Декабрь.
        /// </summary>
        internal static string December {
            get {
                return ResourceManager.GetString("December", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный формат E-mail.
        /// </summary>
        internal static string EmailConstraintMsg {
            get {
                return ResourceManager.GetString("EmailConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле не должно быть пустым.
        /// </summary>
        internal static string EmptyConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тело файла не может быть пустым.
        /// </summary>
        internal static string EmptyFileBodyConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyFileBodyConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нельзя прикрепить пустой файл.
        /// </summary>
        internal static string EmptyFileConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyFileConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла не может быть пустым.
        /// </summary>
        internal static string EmptyFileNameConstraintMsg {
            get {
                return ResourceManager.GetString("EmptyFileNameConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Февраль.
        /// </summary>
        internal static string February {
            get {
                return ResourceManager.GetString("February", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Формат поля должен быть {0}.
        /// </summary>
        internal static string FormatPropConstraintMsg {
            get {
                return ResourceManager.GetString("FormatPropConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверно заполненные поля формы.
        /// </summary>
        internal static string GeneralConstraintMsg {
            get {
                return ResourceManager.GetString("GeneralConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Январь.
        /// </summary>
        internal static string January {
            get {
                return ResourceManager.GetString("January", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июль.
        /// </summary>
        internal static string July {
            get {
                return ResourceManager.GetString("July", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Июнь.
        /// </summary>
        internal static string June {
            get {
                return ResourceManager.GetString("June", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина поля ({0}) не должна превышать {1} символов.
        /// </summary>
        internal static string LengthMaxConstraintMsg {
            get {
                return ResourceManager.GetString("LengthMaxConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Длина поля ({0}) не должна быть меньше {1} символов.
        /// </summary>
        internal static string LengthMinConstraintMsg {
            get {
                return ResourceManager.GetString("LengthMinConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В день можно подать заявок не более {0} .
        /// </summary>
        internal static string LimitRequestCountConstraintMsg {
            get {
                return ResourceManager.GetString("LimitRequestCountConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Март.
        /// </summary>
        internal static string March {
            get {
                return ResourceManager.GetString("March", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя файла не может превышать {0} символов [{1}].
        /// </summary>
        internal static string MaxFileNameConstraintMsg {
            get {
                return ResourceManager.GetString("MaxFileNameConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевышено макс. количество файлов ({0}), которые можно прикреплять к заявке.
        /// </summary>
        internal static string MaxRequestFileCountConstraintMsg {
            get {
                return ResourceManager.GetString("MaxRequestFileCountConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышен макс. размер файла ({0} Кб), который можно прикреплять к заявке [{1}].
        /// </summary>
        internal static string MaxRequestFileSizeConstraintMsg {
            get {
                return ResourceManager.GetString("MaxRequestFileSizeConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Май.
        /// </summary>
        internal static string May {
            get {
                return ResourceManager.GetString("May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявки можно подавать с интервалом не менее {0} мин..
        /// </summary>
        internal static string MinIntervalRequestConstraintMsg {
            get {
                return ResourceManager.GetString("MinIntervalRequestConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая дата окончания {0} не может быть раньше текущей даты {1}.
        /// </summary>
        internal static string NewDeadLineDateConstraintMsg {
            get {
                return ResourceManager.GetString("NewDeadLineDateConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на В продолжение заявки {0}: {1}.
        /// </summary>
        internal static string NewRequestByRequestTemplate {
            get {
                return ResourceManager.GetString("NewRequestByRequestTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Данные не найдены. Возможно, запись была удалена другим пользователеи.
        /// </summary>
        internal static string NoDataFoundMsg {
            get {
                return ResourceManager.GetString("NoDataFoundMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не кириллический символ {0} на позиции {1}.
        /// </summary>
        internal static string NotCyrillicConstraintMsg {
            get {
                return ResourceManager.GetString("NotCyrillicConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на На стороне сервера возникла необработанная ошибка.
        /// </summary>
        internal static string NotHandledExceptionMsg {
            get {
                return ResourceManager.GetString("NotHandledExceptionMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ноябрь.
        /// </summary>
        internal static string November {
            get {
                return ResourceManager.GetString("November", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный формат данных: свойство {0} не должно быть null.
        /// </summary>
        internal static string NullPropConstraintMsg {
            get {
                return ResourceManager.GetString("NullPropConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октябрь.
        /// </summary>
        internal static string October {
            get {
                return ResourceManager.GetString("October", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Только владелец профиля может удалить запись.
        /// </summary>
        internal static string OnlyOwnerEmployeeObjectCanDeleteRecordConstraintMsg {
            get {
                return ResourceManager.GetString("OnlyOwnerEmployeeObjectCanDeleteRecordConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Архивную заявку нельзя редактировать/удалять.
        /// </summary>
        internal static string RequesArchConstraintMsg {
            get {
                return ResourceManager.GetString("RequesArchConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка уже принята в работу Исполнителем. Редактирование/удаление запрещено.
        /// </summary>
        internal static string RequestAcceptConstraintMsg {
            get {
                return ResourceManager.GetString("RequestAcceptConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Поле обязательно для заполнения.
        /// </summary>
        internal static string RequiredConstraintMsg {
            get {
                return ResourceManager.GetString("RequiredConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сентябрь.
        /// </summary>
        internal static string September {
            get {
                return ResourceManager.GetString("September", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля должно быть уникальным.
        /// </summary>
        internal static string UniqueConstraintMsg {
            get {
                return ResourceManager.GetString("UniqueConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Другой пользователь зарегистрирован в системе с этим E-mail. Используйте другой E-mail.
        /// </summary>
        internal static string UniqueEmailConstraintMsg {
            get {
                return ResourceManager.GetString("UniqueEmailConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект уже присутствует в профиле заявителя.
        /// </summary>
        internal static string UniqueEmployeeObjectConstraintMsg {
            get {
                return ResourceManager.GetString("UniqueEmployeeObjectConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не верный формат URL.
        /// </summary>
        internal static string URLConstraintMsg {
            get {
                return ResourceManager.GetString("URLConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля ({0}) не должно превышать {1}.
        /// </summary>
        internal static string ValueMaxConstraintMsg {
            get {
                return ResourceManager.GetString("ValueMaxConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля должно быть неотрицательным.
        /// </summary>
        internal static string ValueNonNegativeConstraintMsg {
            get {
                return ResourceManager.GetString("ValueNonNegativeConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля должно быть положительным.
        /// </summary>
        internal static string ValuePositiveConstraintMsg {
            get {
                return ResourceManager.GetString("ValuePositiveConstraintMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не возможно определить исполнителя.
        /// </summary>
        internal static string WorkerNotDefinedConstraintMsg {
            get {
                return ResourceManager.GetString("WorkerNotDefinedConstraintMsg", resourceCulture);
            }
        }
    }
}
