//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDesk.WorkerWebApp.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HelpDesk.WorkerWebApp.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить.
        /// </summary>
        public static string Action_Add {
            get {
                return ResourceManager.GetString("Action_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить файлы.
        /// </summary>
        public static string Action_AddFile {
            get {
                return ResourceManager.GetString("Action_AddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить ПО.
        /// </summary>
        public static string Action_AddIS {
            get {
                return ResourceManager.GetString("Action_AddIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавить оборудование.
        /// </summary>
        public static string Action_AddTO {
            get {
                return ResourceManager.GetString("Action_AddTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Применить фильтр.
        /// </summary>
        public static string Action_ApplyFilter {
            get {
                return ResourceManager.GetString("Action_ApplyFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Action_Cancel {
            get {
                return ResourceManager.GetString("Action_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Удалить заявку.
        /// </summary>
        public static string Action_DeleteRequest {
            get {
                return ResourceManager.GetString("Action_DeleteRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать.
        /// </summary>
        public static string Action_Edit {
            get {
                return ResourceManager.GetString("Action_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать заявку.
        /// </summary>
        public static string Action_EditRequest {
            get {
                return ResourceManager.GetString("Action_EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Войти.
        /// </summary>
        public static string Action_Login {
            get {
                return ResourceManager.GetString("Action_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая заявка.
        /// </summary>
        public static string Action_NewRequest {
            get {
                return ResourceManager.GetString("Action_NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Восстановить пароль.
        /// </summary>
        public static string Action_RecoveryPassword {
            get {
                return ResourceManager.GetString("Action_RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зарегистрироваться.
        /// </summary>
        public static string Action_Register {
            get {
                return ResourceManager.GetString("Action_Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сбросить фильтр.
        /// </summary>
        public static string Action_ResetFilter {
            get {
                return ResourceManager.GetString("Action_ResetFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сохранить.
        /// </summary>
        public static string Action_Save {
            get {
                return ResourceManager.GetString("Action_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выбрать.
        /// </summary>
        public static string Action_Select {
            get {
                return ResourceManager.GetString("Action_Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перевести.
        /// </summary>
        public static string Action_Transfer {
            get {
                return ResourceManager.GetString("Action_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Action_Update {
            get {
                return ResourceManager.GetString("Action_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отмена.
        /// </summary>
        public static string Action_Сancel {
            get {
                return ResourceManager.GetString("Action_Сancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на help-desk.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не допустимый тип файла.
        /// </summary>
        public static string ErrorMessage_AcceptFileTypesConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_AcceptFileTypesConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль и его подтверждение не совпадают.
        /// </summary>
        public static string ErrorMessage_ConfirmPassword {
            get {
                return ResourceManager.GetString("ErrorMessage_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышен максимальный размер файла {0} KB.
        /// </summary>
        public static string ErrorMessage_MaxFileSizeConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxFileSizeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Превышено допустимое количество файлов.
        /// </summary>
        public static string ErrorMessage_MaxNumberOfFilesConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_MaxNumberOfFilesConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Слишком маленький размер файла.
        /// </summary>
        public static string ErrorMessage_MinFileSizeConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_MinFileSizeConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Значение поля {0} должно содержать не менее {2} и не более {1} символов.
        /// </summary>
        public static string ErrorMessage_StringLengthConstraint {
            get {
                return ResourceManager.GetString("ErrorMessage_StringLengthConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вы не подтвердили, что Вы не робот.
        /// </summary>
        public static string InvalidReCaptcha {
            get {
                return ResourceManager.GetString("InvalidReCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Добавление информационной системы/ПО.
        /// </summary>
        public static string Label_AddIS {
            get {
                return ResourceManager.GetString("Label_AddIS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Оборудование.
        /// </summary>
        public static string Label_AddTO {
            get {
                return ResourceManager.GetString("Label_AddTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сумма.
        /// </summary>
        public static string Label_Amount {
            get {
                return ResourceManager.GetString("Label_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кабинет.
        /// </summary>
        public static string Label_Cabinet {
            get {
                return ResourceManager.GetString("Label_Cabinet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Язык.
        /// </summary>
        public static string Label_ChooseLang {
            get {
                return ResourceManager.GetString("Label_ChooseLang", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подтверждение пароля.
        /// </summary>
        public static string Label_ConfirmPassword {
            get {
                return ResourceManager.GetString("Label_ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Корреспондент.
        /// </summary>
        public static string Label_Correspondent {
            get {
                return ResourceManager.GetString("Label_Correspondent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата окончания.
        /// </summary>
        public static string Label_DateEndPlan {
            get {
                return ResourceManager.GetString("Label_DateEndPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата/время.
        /// </summary>
        public static string Label_DateTime {
            get {
                return ResourceManager.GetString("Label_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Описание проблемы.
        /// </summary>
        public static string Label_DescriptionProblem {
            get {
                return ResourceManager.GetString("Label_DescriptionProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на E-mail.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявитель.
        /// </summary>
        public static string Label_Employee {
            get {
                return ResourceManager.GetString("Label_Employee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата события.
        /// </summary>
        public static string Label_EventDateEvent {
            get {
                return ResourceManager.GetString("Label_EventDateEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string Label_EventNote {
            get {
                return ResourceManager.GetString("Label_EventNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Событие.
        /// </summary>
        public static string Label_EventStatusName {
            get {
                return ResourceManager.GetString("Label_EventStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Фамилия.
        /// </summary>
        public static string Label_FM {
            get {
                return ResourceManager.GetString("Label_FM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Не помните пароль?.
        /// </summary>
        public static string Label_ForgetPassword {
            get {
                return ResourceManager.GetString("Label_ForgetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на От.
        /// </summary>
        public static string Label_From {
            get {
                return ResourceManager.GetString("Label_From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип оборудования (принтер, монитор, сканер и т.п.).
        /// </summary>
        public static string Label_HardType {
            get {
                return ResourceManager.GetString("Label_HardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Имя.
        /// </summary>
        public static string Label_IM {
            get {
                return ResourceManager.GetString("Label_IM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Информационная система/ПО.
        /// </summary>
        public static string Label_IS {
            get {
                return ResourceManager.GetString("Label_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Логин или E-mail.
        /// </summary>
        public static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выйти.
        /// </summary>
        public static string Label_Logout {
            get {
                return ResourceManager.GetString("Label_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Производитель (SONY, SAMSUNG  и т.п.).
        /// </summary>
        public static string Label_Manufacturer {
            get {
                return ResourceManager.GetString("Label_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Модель.
        /// </summary>
        public static string Label_Model {
            get {
                return ResourceManager.GetString("Label_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Примечание.
        /// </summary>
        public static string Label_Note {
            get {
                return ResourceManager.GetString("Label_Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Объект заявки.
        /// </summary>
        public static string Label_ObjectName {
            get {
                return ResourceManager.GetString("Label_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Вид работ (определяет исполнителя работ).
        /// </summary>
        public static string Label_ObjectType {
            get {
                return ResourceManager.GetString("Label_ObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на из.
        /// </summary>
        public static string Label_Of {
            get {
                return ResourceManager.GetString("Label_Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Организация.
        /// </summary>
        public static string Label_Organization {
            get {
                return ResourceManager.GetString("Label_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отчество.
        /// </summary>
        public static string Label_OT {
            get {
                return ResourceManager.GetString("Label_OT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль.
        /// </summary>
        public static string Label_Password {
            get {
                return ResourceManager.GetString("Label_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № телефона.
        /// </summary>
        public static string Label_Phone {
            get {
                return ResourceManager.GetString("Label_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Должность.
        /// </summary>
        public static string Label_Post {
            get {
                return ResourceManager.GetString("Label_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Запомнить меня.
        /// </summary>
        public static string Label_RememberMe {
            get {
                return ResourceManager.GetString("Label_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка.
        /// </summary>
        public static string Label_Request {
            get {
                return ResourceManager.GetString("Label_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Дата подачи.
        /// </summary>
        public static string Label_RequestDate {
            get {
                return ResourceManager.GetString("Label_RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на № заявки.
        /// </summary>
        public static string Label_RequestNumber {
            get {
                return ResourceManager.GetString("Label_RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Состояние.
        /// </summary>
        public static string Label_StatusName {
            get {
                return ResourceManager.GetString("Label_StatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Получать рассылку на E-mail.
        /// </summary>
        public static string Label_Subscribe {
            get {
                return ResourceManager.GetString("Label_Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на До.
        /// </summary>
        public static string Label_To {
            get {
                return ResourceManager.GetString("Label_To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Всего записей.
        /// </summary>
        public static string Label_TotalCount {
            get {
                return ResourceManager.GetString("Label_TotalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кому.
        /// </summary>
        public static string Label_ToWhom {
            get {
                return ResourceManager.GetString("Label_ToWhom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пользователь.
        /// </summary>
        public static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исполнитель.
        /// </summary>
        public static string Label_Worker {
            get {
                return ResourceManager.GetString("Label_Worker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тип работ.
        /// </summary>
        public static string Label_WorkTypeName {
            get {
                return ResourceManager.GetString("Label_WorkTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Подать заявку.
        /// </summary>
        public static string Menu_Request {
            get {
                return ResourceManager.GetString("Menu_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мои заявки.
        /// </summary>
        public static string Menu_RequestHistory {
            get {
                return ResourceManager.GetString("Menu_RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Указанные E-mail не зарегистрирован в системе.
        /// </summary>
        public static string Message_EmailNotRegitered {
            get {
                return ResourceManager.GetString("Message_EmailNotRegitered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Произошла ошибка.
        /// </summary>
        public static string Message_Error {
            get {
                return ResourceManager.GetString("Message_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Неверное имя пользователя или пароль.
        /// </summary>
        public static string Message_LoginError {
            get {
                return ResourceManager.GetString("Message_LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создание новой заявки.
        /// </summary>
        public static string Message_NewRequestCreate {
            get {
                return ResourceManager.GetString("Message_NewRequestCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Записей не найдено.
        /// </summary>
        public static string Message_NotFound {
            get {
                return ResourceManager.GetString("Message_NotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Заявка успешно сохранена.
        /// </summary>
        public static string Message_RequestComplete {
            get {
                return ResourceManager.GetString("Message_RequestComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование заявки.
        /// </summary>
        public static string Message_RequestEdit {
            get {
                return ResourceManager.GetString("Message_RequestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите сумму.
        /// </summary>
        public static string Placeholder_Amount {
            get {
                return ResourceManager.GetString("Placeholder_Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите сотрудника.
        /// </summary>
        public static string Placeholder_EmployeeName {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите объект заявки сотрудника (сначала выберите сотрудника).
        /// </summary>
        public static string Placeholder_EmployeeObjectName {
            get {
                return ResourceManager.GetString("Placeholder_EmployeeObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите или введите тип оборудования.
        /// </summary>
        public static string Placeholder_HardType {
            get {
                return ResourceManager.GetString("Placeholder_HardType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите информационную систему/ПО.
        /// </summary>
        public static string Placeholder_IS {
            get {
                return ResourceManager.GetString("Placeholder_IS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите или введите производителя.
        /// </summary>
        public static string Placeholder_Manufacturer {
            get {
                return ResourceManager.GetString("Placeholder_Manufacturer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите или введите модель.
        /// </summary>
        public static string Placeholder_Model {
            get {
                return ResourceManager.GetString("Placeholder_Model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите имя.
        /// </summary>
        public static string Placeholder_Name {
            get {
                return ResourceManager.GetString("Placeholder_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите объект заявки (задается в {0}).
        /// </summary>
        public static string Placeholder_ObjectName {
            get {
                return ResourceManager.GetString("Placeholder_ObjectName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Выберите организацию.
        /// </summary>
        public static string Placeholder_Organization {
            get {
                return ResourceManager.GetString("Placeholder_Organization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ввведите или выберите должность.
        /// </summary>
        public static string Placeholder_Post {
            get {
                return ResourceManager.GetString("Placeholder_Post", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Для подачи заявки требуется заполнить данные.
        /// </summary>
        public static string Text_AllDataAreRequiredToApply {
            get {
                return ResourceManager.GetString("Text_AllDataAreRequiredToApply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на &lt;a href=&apos;http://google.com&apos;&gt;ООО &quot;Рога и Копыта&quot;&lt;/a&gt;.
        /// </summary>
        public static string Text_Copyright {
            get {
                return ResourceManager.GetString("Text_Copyright", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кол-во переносов.
        /// </summary>
        public static string Text_CountCorrectionDateEndPlan {
            get {
                return ResourceManager.GetString("Text_CountCorrectionDateEndPlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Количество заявок, требующих подтверждения готовности.
        /// </summary>
        public static string Text_CountRequestRequiresConfirmation {
            get {
                return ResourceManager.GetString("Text_CountRequestRequiresConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактирование.
        /// </summary>
        public static string Text_EditRecord {
            get {
                return ResourceManager.GetString("Text_EditRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо полностью заполнить форму.
        /// </summary>
        public static string Text_ItIsNecessaryToFillInTheFormCompletely {
            get {
                return ResourceManager.GetString("Text_ItIsNecessaryToFillInTheFormCompletely", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Руководство пользователя.
        /// </summary>
        public static string Text_ManualUrl {
            get {
                return ResourceManager.GetString("Text_ManualUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Новая запись.
        /// </summary>
        public static string Text_NewRecord {
            get {
                return ResourceManager.GetString("Text_NewRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отсутствуют обслуживаемые организации. Добавление заявок не возможно.
        /// </summary>
        public static string Text_NotAllowableEmployee {
            get {
                return ResourceManager.GetString("Text_NotAllowableEmployee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновите страницу, нажав Ctrl + F5.
        /// </summary>
        public static string Text_PressCtrlF5 {
            get {
                return ResourceManager.GetString("Text_PressCtrlF5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль направлен на указанный E-mail.
        /// </summary>
        public static string Text_RecoveredPassword {
            get {
                return ResourceManager.GetString("Text_RecoveredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Введите адрес E-mail, с которым вы были зарегестрированы в системе. Пароль будет отправлен на этот адрес электронной почты.
        /// </summary>
        public static string Text_RecoveryPassword {
            get {
                return ResourceManager.GetString("Text_RecoveryPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Пароль от личного кабинета {0}.
        /// </summary>
        public static string Text_RecoveryPasswordSubject {
            get {
                return ResourceManager.GetString("Text_RecoveryPasswordSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Регистрация в личном кабинете {0}.
        /// </summary>
        public static string Text_RegisterNow {
            get {
                return ResourceManager.GetString("Text_RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Соглашение об уровне сервиса.
        /// </summary>
        public static string Text_ServiceLevelAgreementUrl {
            get {
                return ResourceManager.GetString("Text_ServiceLevelAgreementUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Техническая поддержка.
        /// </summary>
        public static string Text_TechSupportPhones {
            get {
                return ResourceManager.GetString("Text_TechSupportPhones", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Необходимо добавить хотя бы один объект, на который будет подаваться заявка, в форму.
        /// </summary>
        public static string Text_YouMustAddAtLeastOneObject {
            get {
                return ResourceManager.GetString("Text_YouMustAddAtLeastOneObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Создать заявку.
        /// </summary>
        public static string Title_CreateRequest {
            get {
                return ResourceManager.GetString("Title_CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Редактировать заявку.
        /// </summary>
        public static string Title_EditRequest {
            get {
                return ResourceManager.GetString("Title_EditRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Обновить.
        /// </summary>
        public static string Title_Refresh {
            get {
                return ResourceManager.GetString("Title_Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на История событий заявки.
        /// </summary>
        public static string Title_RequestHistory {
            get {
                return ResourceManager.GetString("Title_RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Перенос срока.
        /// </summary>
        public static string Title_Transfer {
            get {
                return ResourceManager.GetString("Title_Transfer", resourceCulture);
            }
        }
    }
}
